# Generated by Django 4.2.7 on 2025-12-22 18:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationbillingprofile',
            name='subscription_active',
        ),
        migrations.AddField(
            model_name='locationbillingprofile',
            name='subscription_required',
            field=models.BooleanField(default=True, help_text='If false, location can operate without subscription'),
        ),
        migrations.AlterField(
            model_name='locationbillingprofile',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='locationbillingprofile',
            name='transaction_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Percentage charged per transaction', max_digits=5),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='config',
            field=models.JSONField(help_text='API keys, secrets & endpoints'),
        ),
    ]
