# Generated by Django 4.2.7 on 2025-12-22 19:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_locationbillingprofile_subscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('VOUCHER', 'Voucher Purchase'), ('SUBSCRIPTION', 'Subscription Payment')], default='VOUCHER', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationbillingprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable all platform services for this location'),
        ),
        migrations.AlterField(
            model_name='locationbillingprofile',
            name='subscription_required',
            field=models.BooleanField(default=True, help_text='If false, no monthly subscription is required'),
        ),
        migrations.AlterField(
            model_name='locationbillingprofile',
            name='transaction_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Platform percentage cut per transaction', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(help_text='Phone number used to pay', max_length=15),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='config',
            field=models.JSONField(help_text='API credentials & endpoints'),
        ),
    ]
