# Generated by Django 4.2.17 on 2026-03-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_currency_payment_external_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsystemconfig',
            options={'verbose_name': 'Commission Config', 'verbose_name_plural': 'Commission Config'},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name='paymentsplit',
                    old_name='admin_amount',
                    new_name='spotpay_amount',
                ),
                migrations.RenameField(
                    model_name='paymentsplit',
                    old_name='base_system_percentage',
                    new_name='spotpay_percentage',
                ),
                migrations.RemoveField(
                    model_name='paymentsplit',
                    name='subscription_percentage',
                ),
                migrations.RemoveField(
                    model_name='paymentsystemconfig',
                    name='base_system_percentage',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='subscription_mode',
            field=models.CharField(default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsystemconfig',
            name='percentage_mode_percentage',
            field=models.DecimalField(decimal_places=2, default=15, help_text='SpotPay commission % for PERCENTAGE MODE locations (e.g. 15)', max_digits=5),
        ),
        migrations.AddField(
            model_name='paymentsystemconfig',
            name='subscription_mode_percentage',
            field=models.DecimalField(decimal_places=2, default=5, help_text='SpotPay commission % for MONTHLY SUBSCRIPTION locations (e.g. 5)', max_digits=5),
        ),
        migrations.AddField(
            model_name='paymentsystemconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
