# Generated by Django 4.2.17 on 2026-03-28 18:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymentprovider_base_url_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='gateway_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction fee % charged by this payment provider (e.g. 2.0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='gateway_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='gateway_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='provider_type',
            field=models.CharField(choices=[('MOMO', 'Mobile Money (MakyPay)'), ('CARD', 'Card / Gateway'), ('YOO', 'Mobile Money (YooPay)'), ('KWA', 'Mobile Money (KwaPay)')], max_length=10),
        ),
    ]
