# Generated by Django 4.2.7 on 2026-04-07 11:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_withdrawal_fees_spotpay_earning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsystemconfig',
            name='withdrawal_spotpay_fee_percentage',
        ),
        migrations.AddField(
            model_name='paymentsystemconfig',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Monthly subscription fee vendors pay per location in UGX (e.g. 50000)', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentsystemconfig',
            name='withdrawal_spotpay_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat SpotPay fee charged per withdrawal in UGX (e.g. 500)', max_digits=10),
        ),
    ]
