# Generated by Django 4.2.7 on 2026-04-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_add_webhook_secret'),
        ('payments', '0013_rename_withdrawal_spotpay_fee_add_subscription_fee'),
    ]

    operations = [
    ]
