# Generated by Django 4.2.7 on 2026-03-16 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_currency_payment_external_reference_and_more'),
        ('sms', '0002_emailprovider_alter_smsprovider_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smslog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
