from django.db import models
from packages.models import Package


class Voucher(models.Model):
    STATUS_CHOICES = (
        ('UNUSED', 'Unused'),
        ('USED', 'Used'),
        ('EXPIRED', 'Expired'),
    )

    # Voucher belongs to a package (which belongs to a location & vendor)
    package = models.ForeignKey(
        Package,
        on_delete=models.CASCADE,
        related_name='vouchers'
    )

    # Voucher code generated by Mikhmon (username / password)
    code = models.CharField(
        max_length=100,
        unique=True
    )

    # Voucher usage status
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='UNUSED'
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    used_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.code} ({self.status})"
