# Generated by Django 4.2.17 on 2026-03-18 18:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_dead_vendor_balance_fields'),
        ('hotspot', '0005_hotspotlocation_hotspot_dns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name e.g. Main Router', max_length=100)),
                ('host', models.CharField(help_text='IP or hostname of the router', max_length=255)),
                ('port', models.PositiveIntegerField(default=80)),
                ('api_username', models.CharField(default='admin', max_length=100)),
                ('api_password', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='router', to='hotspot.hotspotlocation')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='accounts.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Profile name as it appears on MikroTik', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('validity_hours', models.PositiveIntegerField(default=24, help_text='Hours of uptime allowed')),
                ('data_limit_mb', models.PositiveIntegerField(blank=True, help_text='Data cap in MB (leave blank for unlimited)', null=True)),
                ('shared_users', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='mikrotik.routerconnection')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_profiles', to='accounts.vendor')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='VoucherBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='mikrotik.voucherprofile')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='mikrotik.routerconnection')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mikrotik_batches', to='accounts.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MikrotikVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('UNUSED', 'Unused'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='UNUSED', max_length=10)),
                ('pushed_to_router', models.BooleanField(default=False)),
                ('push_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='mikrotik.voucherbatch')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
