# Generated by Django 4.2.7 on 2026-03-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerconnection',
            name='api_mode',
            field=models.CharField(choices=[('rest', 'REST (v7)'), ('binary', 'Binary API (v6/v7)')], default='binary', help_text='Auto-detected on connection test', max_length=10),
        ),
    ]
