# Generated by Django 4.2.7 on 2025-12-31 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['price']},
        ),
    ]
