# Generated by Django 4.2.17 on 2026-03-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='schedule_type',
            field=models.CharField(choices=[('ALWAYS', 'Always Available'), ('WEEKDAYS', 'Specific Days of the Week'), ('DATE', 'Specific Date')], default='ALWAYS', max_length=10),
        ),
        migrations.AddField(
            model_name='package',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='scheduled_days',
            field=models.CharField(blank=True, help_text='Comma-separated weekday numbers (0=Mon … 6=Sun)', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='scheduled_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='scheduled_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
