# Generated by Django 4.2.7 on 2025-12-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('UNUSED', 'Unused'), ('RESERVED', 'Reserved'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='UNUSED', max_length=10),
        ),
    ]
