# Generated by Django 4.2.7 on 2026-03-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='sms_balance',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='wallet_balance',
        ),
    ]
