# Generated by Django 4.2.7 on 2026-03-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_dead_vendor_balance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Send SMS to vendor on every customer purchase'),
        ),
    ]
