# Generated by Django 4.2.7 on 2025-12-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendorwallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reason',
            field=models.CharField(choices=[('VOUCHER_SALE', 'Voucher Sale'), ('SUBSCRIPTION', 'Subscription Fee'), ('SMS_PURCHASE', 'SMS Purchase'), ('WITHDRAWAL', 'Withdrawal'), ('ADJUSTMENT', 'Adjustment')], default='ADJUSTMENT', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.vendorwallet'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='reference',
            field=models.CharField(default='legacy-withdrawal', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.vendorwallet'),
        ),
    ]
