# Generated by Django 4.2.17 on 2026-03-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_remove_wallettransaction_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_method',
            field=models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money'), ('BANK', 'Bank Transfer')], default='MTN', max_length=10),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_name',
            field=models.CharField(blank=True, help_text='Account holder name', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_phone',
            field=models.CharField(blank=True, help_text='Mobile money number or bank account to receive payment', max_length=20),
        ),
    ]
