# Generated by Django 4.2.7 on 2025-12-28 11:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0001_initial'),
        ('payments', '0003_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='paymentprovider',
            options={'verbose_name': 'Payment Provider', 'verbose_name_plural': 'Payment Providers'},
        ),
        migrations.RemoveField(
            model_name='locationbillingprofile',
            name='subscription_expires_at',
        ),
        migrations.RemoveField(
            model_name='locationbillingprofile',
            name='subscription_period_days',
        ),
        migrations.RemoveField(
            model_name='locationbillingprofile',
            name='subscription_required',
        ),
        migrations.RemoveField(
            model_name='locationbillingprofile',
            name='transaction_percentage',
        ),
        migrations.RemoveField(
            model_name='locationbillingprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='paymentprovider',
            name='config',
        ),
        migrations.AddField(
            model_name='locationbillingprofile',
            name='billing_mode',
            field=models.CharField(choices=[('A', 'Mode A – Voucher Commission'), ('C', 'Mode C – Subscription Based')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='api_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='api_mode',
            field=models.CharField(choices=[('SANDBOX', 'Sandbox / Test'), ('LIVE', 'Live / Production')], default='SANDBOX', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='base_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationbillingprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='locationbillingprofile',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='hotspot.hotspotlocation'),
        ),
        migrations.AlterField(
            model_name='locationbillingprofile',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('VOUCHER', 'Voucher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentprovider'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='LocationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], max_length=10)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='hotspot.hotspotlocation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.subscriptionplan')),
            ],
        ),
    ]
