# Generated by Django 4.2.7 on 2025-12-28 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0001_initial'),
        ('accounts', '0001_initial'),
        ('payments', '0004_subscriptionplan_alter_paymentprovider_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_system_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subscription_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('admin_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_system_percentage', models.DecimalField(decimal_places=2, help_text='Base commission applied to ALL transactions (e.g. 5%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='locationsubscription',
            name='location',
        ),
        migrations.RemoveField(
            model_name='locationsubscription',
            name='plan',
        ),
        migrations.AlterModelOptions(
            name='paymentprovider',
            options={},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='initiated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='paymentprovider',
            name='api_mode',
        ),
        migrations.AddField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotspot.hotspotlocation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_type',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('CLIENT', 'Client')], default='VENDOR', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Location Subscription'), ('TRANSACTION', 'Client Internet Purchase'), ('SMS_PURCHASE', 'SMS Purchase')], default='SUBSCRIPTION', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_callback_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vendor'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='environment',
            field=models.CharField(choices=[('SANDBOX', 'Sandbox'), ('LIVE', 'Live')], default='SANDBOX', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentprovider'),
        ),
        migrations.DeleteModel(
            name='LocationBillingProfile',
        ),
        migrations.DeleteModel(
            name='LocationSubscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split', to='payments.payment'),
        ),
    ]
