# Generated by Django 4.2.7 on 2025-12-20 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('CAFE', 'Cafe / Restaurant'), ('HOTEL', 'Hotel / Lodge'), ('HOSTEL', 'Student Hostel'), ('APARTMENT', 'Apartment Building'), ('OFFICE', 'Office / Co-working'), ('PUBLIC', 'Public Space'), ('OTHER', 'Other')], default='CAFE', max_length=20)),
                ('address', models.TextField()),
                ('town_city', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('location_slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (admin only)')),
                ('portal_url', models.URLField(blank=True)),
                ('max_concurrent_users', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hotspot_locations', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.vendor')),
            ],
            options={
                'verbose_name': 'Hotspot Location',
                'verbose_name_plural': 'Hotspot Locations',
                'ordering': ['-created_at'],
            },
        ),
    ]
