# Generated by Django 4.2.7 on 2025-12-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0002_hotspotlocation_subscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotlocation',
            name='subscription_mode',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Subscription'), ('PERCENTAGE', 'Percentage Based')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='hotspotlocation',
            name='subscription_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra percentage per transaction (only for percentage mode)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='hotspotlocation',
            name='site_name',
            field=models.CharField(max_length=255),
        ),
    ]
