# Generated by Django 4.2.7 on 2025-12-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0003_hotspotlocation_subscription_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspotlocation',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes'),
        ),
        migrations.AlterField(
            model_name='hotspotlocation',
            name='subscription_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue share percentage (used only in percentage mode)', max_digits=5),
        ),
    ]
