# Generated by Django 4.2.7 on 2026-04-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0006_hotspotlocation_login_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotlocation',
            name='mikhmon_session',
            field=models.CharField(blank=True, help_text='Mikhmon session name for this location (set by admin after VPN config)', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotspotlocation',
            name='login_type',
            field=models.CharField(choices=[('PLAIN', 'Plain — username = password (Mikhmon default)'), ('NONE', 'None — username only, no password (blank password)'), ('CHAP', 'CHAP MD5 — username ≠ password (KaWifi style)'), ('SEPARATE', 'Separate username & password fields')], default='PLAIN', help_text='How voucher authentication works on this MikroTik', max_length=10),
        ),
    ]
