# Generated by Django 4.2.7 on 2026-04-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0007_add_mikhmon_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotlocation',
            name='vpn_api_password',
            field=models.CharField(blank=True, help_text='Auto-generated MikroTik API password', max_length=50),
        ),
        migrations.AddField(
            model_name='hotspotlocation',
            name='vpn_api_user',
            field=models.CharField(blank=True, help_text='Auto-generated MikroTik API username (spotpay_XXXXXX)', max_length=50),
        ),
        migrations.AddField(
            model_name='hotspotlocation',
            name='vpn_configured',
            field=models.BooleanField(default=False, help_text='Set to True once vendor has run the VPN setup script'),
        ),
    ]
