# Generated by Django 4.2.7 on 2026-04-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0008_add_vpn_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotlocation',
            name='ovpn_client_config',
            field=models.TextField(blank=True, help_text='Generated OpenVPN client config (.ovpn) for ROS v6'),
        ),
        migrations.AddField(
            model_name='hotspotlocation',
            name='ros_version',
            field=models.CharField(choices=[('v6', 'RouterOS v6'), ('v7', 'RouterOS v7')], default='v7', help_text='MikroTik RouterOS version — determines VPN type (WireGuard v7, OpenVPN v6)', max_length=5),
        ),
    ]
