# Generated by Django 4.2.7 on 2025-12-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotlocation',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotspotlocation',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotspotlocation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotspotlocation',
            name='site_name',
            field=models.CharField(max_length=100),
        ),
    ]
