# Generated by Django 4.2.7 on 2025-12-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0004_alter_hotspotlocation_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotlocation',
            name='hotspot_dns',
            field=models.CharField(default='hot.spot', help_text='DNS configured on MikroTik hotspot (e.g. hot.spot, wifi.shop.com)', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotspotlocation',
            name='portal_url',
            field=models.URLField(blank=True, help_text='Django captive portal URL'),
        ),
    ]
