# Generated by Django 4.2.7 on 2025-12-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaltemplate',
            name='name',
            field=models.CharField(default='Default Portal', max_length=100),
        ),
    ]
